/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import Card from "../components/Card";

export default function Home({ countries }) {
  const [isLoading, setIsLoading] = useState(true);
  const [sortCountries, setSortCountries] = useState(countries);
  const [filteredCountries, setFilterCountries] = useState(countries);
  const [filterText, setFilterText] = useState("");

  useEffect(() => {
    if (filterText !== "") {
      const filter = countries.filter((country) => {
        return country.name.common
          .toUpperCase()
          .includes(filterText.toUpperCase());
      });

      setFilterCountries(filter);
    } else {
      setFilterCountries(sortCountries);
    }
  }, [filterText]);

  useEffect(() => {
    if (!countries) setIsLoading(true);
    if (countries) {
      const filter = countries.sort(function (a, b) {
        const nameA = a.name.common.toUpperCase(); // ignore upper and lowercase
        const nameB = b.name.common.toUpperCase(); // ignore upper and lowercase
        if (nameA < nameB) {
          return -1;
        }
        if (nameA > nameB) {
          return 1;
        }

        // names must be equal
        return 0;
      });
      setIsLoading(false);
      setSortCountries(filter);
    }
  }, [countries]);

  return (
    <div className="mx-auto flex min-h-screen w-full max-w-7xl justify-center lg:max-w-[1440px]">
      <Head>
        <title>Countries of the Earth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <div className="text-center">
          <svg
            role="status"
            className="mr-2 inline h-28 w-28 animate-spin fill-indigo-600 text-gray-200 dark:text-gray-600"
            viewBox="0 0 100 101"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
              fill="currentColor"
            />
            <path
              d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
              fill="currentFill"
            />
          </svg>
        </div>
      ) : (
        <div className="flex w-full flex-col gap-8">
          <h1 className="mb-4 text-center text-xl uppercase">
            Count of Results: {Object.keys(filteredCountries).length}
          </h1>
          <div className="relative mx-auto w-[90%] rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
            <label
              htmlFor="search"
              className="absolute -top-2 left-2 -mt-px inline-block bg-white px-1 text-xs font-medium text-gray-900"
            >
              Search
            </label>
            <input
              type="text"
              name="search"
              id="search"
              className="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm"
              placeholder="e.g. Japan"
              onKeyUp={(e) => setFilterText(e.target.value)}
            />
          </div>
          <div className="grid w-full grid-cols-1 gap-3 px-4 md:px-10 lg:grid-cols-2 lg:px-12 xl:grid-cols-3 xl:px-16">
            {filteredCountries.length > 0 &&
              filteredCountries.map((country, idx) => {
                return <Card country={country} key={idx} />;
              })}
          </div>
        </div>
      )}
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await axios
    .get("https://restcountries.com/v3.1/all")
    .then((res) => {
      return res.data;
    })
    .catch((err) => {
      console.log(err);
    });

  // const { name, flags, maps } = data;

  if (data) {
    return {
      props: {
        countries: data,
      },
    };
  } else {
    return {
      props: {
        countries: [],
      },
    };
  }
};
